name: Auto Update DayZ Data (SelfBot)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install discord.py-self pandas huggingface_hub

      - name: Ejecutar script de Discord
        env:
          TOKEN_ID: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot_update.py

      - name: Guardar cambios en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add datos.json
          if git diff --staged --quiet; then
            echo "Sin cambios detectados en el JSON."
          else
            git commit -m "Update datos.json [Skip CI]"
            git push origin main
          fi

      - name: Inyectar datos en Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          import os
          api = HfApi()
          try:
              api.upload_file(
                  path_or_fileobj='datos.json',
                  path_in_repo='datos.json',
                  repo_id='Salesao87/dayz-intel-map',
                  repo_type='space',
                  token=os.environ['HF_TOKEN']
              )
              print('✅ ¡ÉXITO! Datos inyectados en HF Spaces')
          except Exception as e:
              print(f'❌ ERROR HF: {e}')
          "
