name: Auto Update DayZ Data

on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta automáticamente cada 30 minutos
  workflow_dispatch:      # Permite ejecutarlo manualmente con el botón "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install discord.py-self pandas huggingface_hub

      - name: Ejecutar script de Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot_update.py

      - name: Subir cambios a GitHub (Copia de seguridad)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add datos.json
          git commit -m "Update datos.json desde Discord" || exit 0
          git push

      - name: Inyectar datos en Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub import HfApi; api = HfApi(); api.upload_file(path_or_fileobj='datos.json', path_in_repo='datos.json', repo_id='Salesao87/dayz-intel-map', repo_type='space', token='${{ secrets.HF_TOKEN }}')"
